receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  file: 
    path: ./data.txt

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, file]
